version = 0.1
[default.pipeline_bootstrap.parameters]
pipeline_user = "arn:aws:iam::286128020352:user/aws-sam-cli-managed-dev-pipeline-resou-PipelineUser-anywGpPvADcw"
permissions_provider = "AWS IAM"

[dev.pipeline_bootstrap.parameters]
pipeline_execution_role = "arn:aws:iam::286128020352:role/aws-sam-cli-managed-dev-pipel-PipelineExecutionRole-H5GpqJzuouE6"
cloudformation_execution_role = "arn:aws:iam::286128020352:role/aws-sam-cli-managed-dev-p-CloudFormationExecutionRo-dTsRSVLc31cE"
artifacts_bucket = "aws-sam-cli-managed-dev-pipeline-r-artifactsbucket-n0qq23ula8w2"
image_repository = ""
region = "us-east-2"
parameter_overrides = "Stage=dev"

[prod.pipeline_bootstrap.parameters]
pipeline_execution_role = "arn:aws:iam::286128020352:role/aws-sam-cli-managed-prod-pipe-PipelineExecutionRole-JsU1CoXY66lX"
cloudformation_execution_role = "arn:aws:iam::286128020352:role/aws-sam-cli-managed-prod--CloudFormationExecutionRo-LeHOnQnPRL2y"
artifacts_bucket = "aws-sam-cli-managed-prod-pipeline--artifactsbucket-1lmuxt3fzzwu"
image_repository = ""
region = "us-east-1"
parameter_overrides = "Stage=prod"
