AWSTemplateFormatVersion: '2010-09-09'
Transform: AWS::Serverless-2016-10-31
Description: >
  emr-tech-tools
  Sample SAM Template for emr-tech-tools

Parameters:
  Stage:
    Type: String
    Default: dev

Globals:
  Function:
    Timeout: 10
    MemorySize: 128

Resources:
  # Existing EMRSpinUp Lambda function
  EMRSpinUp:
    Type: AWS::Serverless::Function
    Properties:
      CodeUri: emr/EMRSpinUp
      Handler: EMRSpinUp.lambda_handler
      Runtime: python3.9
      Architectures:
        - x86_64
      Events:
        S3UploadEvent:
          Type: S3
          Properties:
            Bucket: !Ref emrLambdaTrigger
            Events: s3:ObjectCreated:*
            Filter:
              S3Key:
                Rules:
                  - Name: prefix
                    Value: submissions/

  # New EMRNotify Lambda function
  EMRNotify:
    Type: AWS::Serverless::Function
    Properties:
      CodeUri: emr/EMRNotify
      Handler: EMRNotify.lambda_handler
      Runtime: python3.9
      Architectures:
        - x86_64
      Events:
        NotifyS3Event:
          Type: S3
          Properties:
            Bucket: !Ref emrLambdaTrigger
            Events: s3:ObjectCreated:*
            Filter:
              S3Key:
                Rules:
                  - Name: prefix
                    Value: Notify/

  # New EMRTerminate Lambda function
  EMRTerminate:
    Type: AWS::Serverless::Function
    Properties:
      CodeUri: emr/EMRTerminate
      Handler: EMRTerminate.lambda_handler
      Runtime: python3.9
      Architectures:
        - x86_64
      Events:
        TerminationS3Event:
          Type: S3
          Properties:
            Bucket: !Ref emrLambdaTrigger
            Events: s3:ObjectCreated:*
            Filter:
              S3Key:
                Rules:
                  - Name: prefix
                    Value: terminations/

  # New EMRRemainder Lambda function
  EMRRemainder:
    Type: AWS::Serverless::Function
    Properties:
      CodeUri: emr/EMRRemainder
      Handler: EMRRemainder.lambda_handler
      Runtime: python3.9
      Architectures:
        - x86_64
      Events:
        Schedule:
          Type: ScheduleV2
          Properties:
            ScheduleExpression: rate(1 hour)
            Input: '{"hello": "simple"}'

  emrLambdaTrigger:
    Type: AWS::S3::Bucket

  BootstrapActionsBucket:
    Type: AWS::S3::Bucket
    Properties:
      BucketName: !Sub "bootstrap-actions-emr-1-${Stage}"

  BootstrapActionsBucketPolicy:
    Type: AWS::S3::BucketPolicy
    Properties:
      Bucket: !Ref BootstrapActionsBucket
      PolicyDocument:
        Version: "2012-10-17"
        Statement: 
          - Effect: Allow
            Action: 
              - "s3:GetObject"
              - "s3:PutObject"
            Resource: 
              - !Sub "arn:aws:s3:::bootstrap-actions-emr-1-${Stage}/*"
            Principal: 
              AWS: !Sub "arn:aws:iam::${AWS::AccountId}:root"


  # # IAM Role modification for S3 PutObject permission
  # BootstrapActionsRole:
  #   Type: AWS::IAM::Role
  #   Properties:
  #     AssumeRolePolicyDocument:
  #       Version: '2012-10-17'
  #       Statement:
  #         - Effect: Allow
  #           Principal:
  #             Service: [lambda.amazonaws.com]
  #           Action: sts:AssumeRole
  #     Policies:
  #       - PolicyName: BootstrapActionsS3Policy
  #         PolicyDocument:
  #           Version: '2012-10-17'
  #           Statement:
  #             - Effect: Allow
  #               Action: s3:PutObject
  #               Resource: !Sub "arn:aws:s3:::bootstrap-actions-emr-1-${Stage}/*"

Outputs:
  EMRSpinUp:
    Description: "EMRSpinUp Lambda Function ARN"
    Value: !GetAtt EMRSpinUp.Arn
  EMRSpinUpIamRole:
    Description: "Implicit IAM Role created for EMRSpinUp function"
    Value: !GetAtt EMRSpinUpRole.Arn

  # Outputs for the new functions
  EMRNotify:
    Description: "EMRNotify Lambda Function ARN"
    Value: !GetAtt EMRNotify.Arn
  EMRNotifyIamRole:
    Description: "Implicit IAM Role created for EMRNotify function"
    Value: !GetAtt EMRNotifyRole.Arn

  EMRTerminate:
    Description: "EMRTerminate Lambda Function ARN"
    Value: !GetAtt EMRTerminate.Arn
  EMRTerminateIamRole:
    Description: "Implicit IAM Role created for EMRTerminate function"
    Value: !GetAtt EMRTerminateRole.Arn

  EMRRemainder:
    Description: "EMRRemainder Lambda Function ARN"
    Value: !GetAtt EMRRemainder.Arn
  EMRRemainderIamRole:
    Description: "Implicit IAM Role created for EMRRemainder function"
    Value: !GetAtt EMRRemainderRole.Arn
