name: Upload File to S3

on:
  push:
    branches:
      - main  # Trigger the workflow on pushes to the main branch

jobs:
  upload-to-s3:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v3

      - name: Configure AWS credentials
        uses: aws-actions/configure-aws-credentials@v3
        with:
          aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
          aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}

      - name: Upload file to S3
        run: |
          aws s3 cp emr-tech-tools/emr/bootstrapActions/bootstrap_scripts.sh s3://bootstrap-actions-emr-1-dev/emr/
          aws s3 cp emr-tech-tools/emr/bootstrapActions/bootstrap_scripts.sh s3://bootstrap-actions-emr-1-prod/emr/
